#!/bin/bash
#this script copies /var/log contents clear current contents of the file
#usage ./clearlogs

LOGFILE=/var/log/messages

cp $LOGFILE $LOGFILE.old
cat /dev/null > $LOGFILE
echo log file copied and cleaned up

exit 0
