#!/bin/bash
# we can use && and || instead of if then else in previous example
# 
[ -z $1 ] && echo $1 no arguments provided && exit 2
[ -d $1 ] && echo $1 is a directory && exit 0
[ -f $1 ] && echo $1 is a file || echo $1  is not a file, nor a directory && exit 0

