#!/bin/bash
while true ; do
trap "echo NOPE INT"
pinghost ()
{
	echo which host do you want to ping
	read HOSTNAME
	ping $HOSTNAME
}
echo 'Select option: '
select TASK in 'Reset password: ' 'Show disk usage: ' 'Ping a host: '  'Logout: '

do
	case $REPLY in
		1) TASK=passwd;;
		2) TASK="df -h";;
		3) TASK=pinghost;;
		4) TASK=exit;;
	esac

	if [ -n "$TASK" ]
	then
		clear
		$TASK
		break
	else
		echo INVALID CHOICE #, try again
	fi

done 
done
