#!/bin/bash
#
# script that show how here doc can be used
# as an alter to the echo cmd


cat <<End-of-message
------------------------------
this is line 1 of the message
this is line 2 of the message
this is the last line of the message
------------------------------------
End-of-message

