#!/bin/bash
#	demo script that shows making menus with select

echo 'Select a directory: '
select DIR in /bin  /usr  /etc
do
	# only continue if the user has selected something
	if [ -n $DIR ]
	then
		DIR=$DIR
		echo you have selected $DIR
		export DIR
		break
	else
		echo invalid choice
	fi
done
