#!/bin/bash
# ${VAR#pattern}
# ${VAR##pattern}
# ${VAR%pattern}
# $VAR%%pattern}

#
#

BLAH=rababarabarabarara

echo BHAH is $BLAH
echo ' the result of ##*ba is ' ${BLAH##*ba}
echo ' the result of #*ba  is ' ${BLAH#*ba}
echo ' the result of %%ba is  ' ${BLAH%%ba*}
echo ' the result of %ba* is  ' ${BLAH%ba*}

