#!/bin/bash
#
# Monitoring process
#
PROCESS=httpd
#
# make sure that $PROCESS is equal to the service script that needs starting

COUNTER=0
while ps aux | grep $PROCESS | grep -v grep > /dev/null

do
	COUNTER=$((COUNTER+1))
	sleep 1
	echo COUNTER IS $COUNTER
done

logger PROCESSMONITOR: $PROCESS stopped at $(date)
service $PROCESS start
mail -s "$PROCESS just stopped"  root < .


